# Data Exploration - Milan

This notebook explores demographic and real estate data for Paris to analyze gentrification patterns.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd


# Set plotting style
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.float_format', lambda x: '%.0f' % x)
pd.set_option('display.float_format', '{:.2f}'.format)

ModuleNotFoundError: No module named 'seaborn'

#### Useful Functions

In [ ]:
def interpolate_panel_data(
    source_gdf: gpd.GeoDataFrame, 
    target_gdf: gpd.GeoDataFrame, 
    data_cols,  # Can be a str or a list of str
    year_col: str, 
    target_id_col: str,
    method: str = 'intensive'
) -> gpd.GeoDataFrame: # Return type updated to GeoDataFrame
    """
    Performs areal interpolation on panel data (multi-year) from source geometries 
    to target geometries and returns a GeoDataFrame with original target attributes.

    Parameters:
    -----------
    source_gdf : gpd.GeoDataFrame
        Source geometries containing the data and the year column.
    target_gdf : gpd.GeoDataFrame
        Target geometries (e.g., NILs) where you want to estimate the data.
    data_cols : str or list
        Name of the column(s) to interpolate (e.g., 'Price', 'Income').
    year_col : str
        Name of the column containing the year/period.
    target_id_col : str
        Unique identifier column in the target GeoDataFrame (e.g., 'NIL').
    method : str, default 'intensive'
        'intensive': For ratios, prices, means (Price/m2). Weights by (Intersection / Target Area).
        'extensive': For counts, sums (Population). Weights by (Intersection / Source Area).

    Returns:
    --------
    gpd.GeoDataFrame
        A GeoDataFrame with columns [target_id_col, year_col, data_cols, geometry, ...] 
        containing the interpolated values for each year and original target info.
    """
    
    # 1. Standardization: Ensure data_cols is always a list
    if isinstance(data_cols, str):
        data_cols = [data_cols]
    
    # Ensure CRS matches
    if source_gdf.crs != target_gdf.crs:
        print(f"CRS mismatch! Reprojecting source to {target_gdf.crs.name}...")
        source_gdf = source_gdf.to_crs(target_gdf.crs)

    results = []
    unique_years = source_gdf[year_col].unique()
    
    print(f"Starting interpolation for {len(unique_years)} periods on {len(data_cols)} variables...")

    # Pre-calculate Target Areas
    target_gdf_calc = target_gdf.copy()
    target_gdf_calc['target_total_area'] = target_gdf_calc.geometry.area

    for year in sorted(unique_years):
        # Filter Source for current year
        year_source = source_gdf[source_gdf[year_col] == year].copy()
        
        if year_source.empty:
            continue

        # Calculate Source Area (if needed for extensive method)
        if method == 'extensive':
            year_source['source_total_area'] = year_source.geometry.area

        # --- SPATIAL INTERSECTION ---
        intersection = gpd.overlay(target_gdf_calc, year_source, how='intersection')
        intersection['piece_area'] = intersection.geometry.area
        
        # --- WEIGHT CALCULATION ---
        if method == 'intensive':
            # Weight = Piece / Target Area
            intersection['weight'] = intersection['piece_area'] / intersection['target_total_area']
        elif method == 'extensive':
            # Weight = Piece / Source Area
            intersection['weight'] = intersection['piece_area'] / intersection['source_total_area']

        # --- APPLY WEIGHTS TO ALL COLUMNS ---
        # We loop through the columns to calculate the weighted value for each
        for col in data_cols:
            # Overwrite the column with its weighted value
            intersection[col] = intersection[col] * intersection['weight']

        # --- AGGREGATION ---
        # Prepare dictionary for aggregation: { 'Col1': 'sum', 'Col2': 'sum' }
        agg_dict = {col: 'sum' for col in data_cols}
        
        year_result = intersection.groupby(target_id_col).agg(agg_dict).reset_index()
        
        # Add Year column back
        year_result[year_col] = year
        
        results.append(year_result)

    # Combine all years into a calculated DataFrame
    calculated_df = pd.concat(results, ignore_index=True)
    
    # --- NEW PART: MERGE BACK ORIGINAL TARGET COLUMNS ---
    # We merge the target_gdf (which has geometry, names, etc.) 
    # with our calculated data (which has ID, Year, Values).
    
    # We use 'right' merge to keep all rows from our calculated panel data
    # and attach the target attributes (Geometry, Name) to them.
    final_gdf = target_gdf.merge(calculated_df, on=target_id_col, how='right')
    
    # Sort for cleanliness
    final_gdf = final_gdf.sort_values(by=[target_id_col, year_col])
    
    return final_gdf

In [ ]:
import folium
from folium.features import GeoJsonTooltip
from IPython.display import HTML, display

def generate_annual_maps_grid(
    gdf: gpd.GeoDataFrame, 
    value_col: str, 
    id_col: str, 
    name_col: str,
    year_col: str = 'Anno',
    cols: int = 3
) -> None:
    """
    Generates a Folium map for every unique year in the GeoDataFrame 
    and displays the resulting maps in a grid layout.

    Parameters:
    -----------
    gdf : geopandas.GeoDataFrame
        The panel data containing geometry, years, and the value to map.
    value_col : str
        The column name of the value to color (e.g., 'Estimated_Price').
    id_col : str
        The unique ID column for the geometry (e.g., 'Zona').
    name_col : str
        The column containing human-readable names (e.g., 'Zona' name).
    year_col : str, default 'Anno'
        The column containing the year/period.
    cols : int, default 3
        The number of maps to display per row in the grid.
    """
    
    available_years = sorted(gdf[year_col].unique())
    map_list = []
    
    print(f"Generating {len(available_years)} maps for years {available_years}...")

    # --- 1. GENERATE ALL MAPS ---
    for year in available_years:
        
        # 1.1. Filter Data for the current year
        plot_data = gdf[gdf[year_col] == year].copy()
        
        # 1.2. Ensure ID is string for GeoJSON mapping (CRITICAL STEP)
        plot_data[id_col] = plot_data[id_col].astype(str)

        # 1.3. Initialize Map (Using a simpler tile and fixed zoom for grid comparison)
        m = folium.Map(location=[45.4642, 9.1900], zoom_start=11, tiles='CartoDB Positron')

        # 1.4. Add Choropleth Layer
        folium.Choropleth(
            geo_data=plot_data,
            data=plot_data,
            columns=[id_col, value_col],
            key_on=f'feature.properties.{id_col}',
            fill_color='YlGnBu',
            fill_opacity=0.7,
            line_opacity=0.2,
            legend_name=f'{value_col} (€)',
            nan_fill_color="grey"
        ).add_to(m)

        # 1.5. Add Tooltip Layer (Interactivity)
        style_function = lambda x: {'fillColor': '#ffffff', 'color':'#000000', 'fillOpacity': 0.0, 'weight': 0.1}

        folium.GeoJson(
            plot_data,
            style_function=style_function,
            tooltip=GeoJsonTooltip(
                fields=[name_col, value_col],
                aliases=['Zone:', f'{value_col} (€/m²):'],
                localize=True,
                sticky=True
            ),
        ).add_to(m)
        
        map_list.append(m)

    # --- 2. DISPLAY IN GRID LAYOUT ---
    
    print("\nVisualizing grid...")

    # Start the CSS Grid container
    # The grid will have 'cols' number of equal-width tracks.
    html_string = f'<div style="display: grid; grid-template-columns: repeat({cols}, 1fr); gap: 10px; width: 100%;">'
    
    # Iterate through the maps and embed their HTML representations
    for i, map_obj in enumerate(map_list):
        # Get the HTML representation of the Folium map
        map_html = map_obj._repr_html_()
        
        # Get the corresponding year for the title
        year_label = available_years[i]
        
        # Create a cell for the map with a clear title showing the year
        html_string += f"""
        <div style="border: 1px solid #ddd; padding: 5px; min-width: 300px;">
            <h3 style="text-align: center; margin: 5px;">Year {year_label}</h3>
            {map_html}
        </div>
        """
    
    # Close the container and display
    html_string += '</div>'
    
    display(HTML(html_string))

### NIL

In [ ]:
nil = gpd.read_file("../data/raw/milan/nil_milano.geojson").set_index("ID_NIL").sort_index()

In [ ]:
## Neighbourhoods (Shape_area and length are expressed respectively in square meters and meters)
nil = nil.reset_index()
nil.head()
nil = nil[["ID_NIL", "NIL", "Shape_Area", "geometry"]]

nil = gpd.GeoDataFrame(nil, geometry=nil['geometry'])
nil = nil.to_crs(epsg=25832)

nil.head()

,ID_NIL,NIL,Shape_Area,geometry
0,1,DUOMO,2341615.57,"POLYGON ((515228.364 5035405.426, 515220.974 5..."
1,2,BRERA,1637332.92,"POLYGON ((514980.845 5035076.611, 515011.579 5..."
2,3,GIARDINI P.TA VENEZIA,249637.39,"POLYGON ((515702.277 5035909.868, 515632.009 5..."
3,4,GUASTALLA,1547962.26,"POLYGON ((516181.357 5034947.813, 516175.502 5..."
4,5,PORTA VIGENTINA - PORTA LODOVICA,1135196.41,"POLYGON ((515783.987 5033226.044, 515699.678 5..."

In [ ]:
raw_dati_residenti = pd.read_csv("../data/raw/milan/residenti_per_cittadinanza_e_quartiere.csv", sep=';')
raw_dati_residenti = raw_dati_residenti[raw_dati_residenti["Anno"].between(2015, 2023)]
raw_dati_residenti.head()

         Anno  IdNil    Nil Eta   Genere Cittadinanza  Residenti
1628996  2015      1  Duomo   0  Femmine    Filippine          1
1628997  2015      1  Duomo   0  Femmine     Germania          1
1628998  2015      1  Duomo   0  Femmine       Italia         50
1628999  2015      1  Duomo   0  Femmine         Mali          1
1629000  2015      1  Duomo   0  Femmine         Perù          1

In [ ]:
dati_residenti = raw_dati_residenti.rename(columns = {"IdNil":"ID_NIL", "Nil":"NIL"}).groupby(["Anno", "ID_NIL", "NIL", "Eta"])[["Residenti"]].sum().sort_values(["Anno", "Eta", "ID_NIL"]).reset_index()
dati_residenti['Eta'] = (dati_residenti['Eta'].replace("100 e più", 100)).astype("int64")

# Quante residenti di Età x per NIL in un dato anno
dati_residenti.head()

   Anno  ID_NIL                                  NIL  Eta  Residenti
0  2015       1                                Duomo    0        143
1  2015       2                                Brera    0        140
2  2015       4                            Guastalla    0        114
3  2015       5     Porta Vigentina - Porta Lodovica    0        101
4  2015       6  Porta Ticinese - Conca del Naviglio    0        178

In [ ]:
densita_nil = dati_residenti.groupby(["Anno", "ID_NIL"])[["Residenti"]].sum().reset_index() #quanti residenti per NIL in un dato anno

densita_nil = densita_nil.merge( #merge con geo
    nil,
    on="ID_NIL",
    how='left'
)

# Converting m2 to km2
densita_nil["Shape_Area"] = densita_nil["Shape_Area"] / 1000000.0
densita_nil["Pop_density"] = densita_nil["Residenti"] / densita_nil["Shape_Area"]

densita_nil.head()

,Anno,ID_NIL,Residenti,NIL,Shape_Area,geometry,Pop_density
0,2015,1,16634,DUOMO,2.34,"POLYGON ((515228.364 5035405.426, 515220.974 5...",7103.64
1,2015,2,17871,BRERA,1.64,"POLYGON ((514980.845 5035076.611, 515011.579 5...",10914.70
2,2015,3,55,GIARDINI P.TA VENEZIA,0.25,"POLYGON ((515702.277 5035909.868, 515632.009 5...",220.32
3,2015,4,14929,GUASTALLA,1.55,"POLYGON ((516181.357 5034947.813, 516175.502 5...",9644.29
4,2015,5,13546,PORTA VIGENTINA - PORTA LODOVICA,1.14,"POLYGON ((515783.987 5033226.044, 515699.678 5...",11932.74

In [ ]:
young_adults = dati_residenti[dati_residenti['Eta'].between(20, 39)].drop(columns="NIL") #restringiamo a 20-39

#quanti residenti 20-39 per NIL in un dato anno
young_adults = young_adults.groupby(["Anno", "ID_NIL"])[["Residenti"]].sum().reset_index()
young_adults = young_adults.rename(columns = {"Residenti":"Young Adults"})

# Adding Geo
young_adults = young_adults.merge(
    nil,
    on="ID_NIL",
    how='left'
)

# Adding Tot Residents
young_adults = young_adults.merge(
    densita_nil[["Anno", "ID_NIL", "Residenti"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

young_adults["pct_young_adults"] = young_adults["Young Adults"] / young_adults["Residenti"]
young_adults = young_adults.sort_values(["pct_young_adults"], ascending=False).reset_index(drop=True)

young_adults.head()

,Anno,ID_NIL,Young Adults,NIL,Shape_Area,geometry,Residenti,pct_young_adults
0,2019,24,1622,PARCO FORLANINI - CAVRIANO,2926006.12,"POLYGON ((520336.5 5035359.951, 520336.216 503...",2451,0.66
1,2018,24,1731,PARCO FORLANINI - CAVRIANO,2926006.12,"POLYGON ((520336.5 5035359.951, 520336.216 503...",2656,0.65
2,2020,24,1560,PARCO FORLANINI - CAVRIANO,2926006.12,"POLYGON ((520336.5 5035359.951, 520336.216 503...",2424,0.64
3,2021,24,1352,PARCO FORLANINI - CAVRIANO,2926006.12,"POLYGON ((520336.5 5035359.951, 520336.216 503...",2180,0.62
4,2022,24,1404,PARCO FORLANINI - CAVRIANO,2926006.12,"POLYGON ((520336.5 5035359.951, 520336.216 503...",2338,0.60

### Median Price of Houses (OMI ZONES)

In [ ]:
omi_zones = gpd.read_file('../data/raw/milan/zone_omi24_comunemilano.geojson')
raw_omi_quot = pd.read_csv('../data/raw/milan/quotazioni_omi_riepilogo.csv', sep = ";")

# NOTE: For Rent the number is euros/square meter for month, while for Selling it is euros/square meter. 
# N and L stand for "netta" and "lorda"

In [ ]:
# We drop a zone which is absent
#omi_zones = omi_zones[omi_zones['LinkZona'] != 'MI00004391']

# --- Pre-requisiti: Allinea CRS a un sistema metrico (essenziale per calcolo area) ---
# Usiamo un CRS comune per Milano, ad esempio UTM 32N (EPSG:25832) o un sistema nazionale (EPSG:3003)
# Scegliendo 25832 (ETRS89 / UTM zone 32N)
omi_zones = omi_zones[["Zona", "geometry"]].to_crs(epsg=25832)

omi_zones.head()

  Zona                                           geometry
0  B12  POLYGON Z ((514267.639 5034915.946 0, 514284.6...
1  B13  POLYGON Z ((513895.15 5033961.011 0, 513922.50...
2  B15  POLYGON Z ((515245.709 5035406.626 0, 515240.7...
3  B16  MULTIPOLYGON Z (((513779.417 5034933.409 0, 51...
4  B17  MULTIPOLYGON Z (((509098.615 5038579.09 0, 509...

In [ ]:
raw_omi_quot.head(1)

,Anno,Periodo,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Compr_min,Compr_max,Sup_NL_compr,Loc_min,Loc_max,Sup_NL_loc
0,2004,2 semestre,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B01,MI00000290,20,Abitazioni civili,NORMALE,P,3850,5450,L,"10,2","14,5",L

In [ ]:
omi_quot = raw_omi_quot[["Anno", "Periodo", "Zona", "Cod_Tip", "Descr_Tipologia", "Stato", "Compr_min", "Compr_max", "Loc_min", "Loc_max"]]
omi_quot = omi_quot[omi_quot["Anno"].between(2015, 2023)]

omi_quot.head()

,Anno,Periodo,Zona,Cod_Tip,Descr_Tipologia,Stato,Compr_min,Compr_max,Loc_min,Loc_max
16861,2015,2 semestre,B12,20,Abitazioni civili,NORMALE,7400,8800,"22,7",29
16862,2015,2 semestre,B12,20,Abitazioni civili,OTTIMO,8800,11800,29,35
16863,2015,2 semestre,B12,21,Abitazioni di tipo economico,OTTIMO,7700,8800,22,30
16864,2015,2 semestre,B12,21,Abitazioni di tipo economico,NORMALE,6400,7600,"17,8",21
16865,2015,2 semestre,B12,19,Abitazioni signorili,OTTIMO,11800,13800,39,45

In [ ]:
# By zone, independently from type of building
# Averaging between semesters
# Not considering rent
# ONLY "ABITAZIONI CIVILI"
# Taking the min and max between all grades of buildings.

omi_slim = omi_quot[ 
    (omi_quot["Descr_Tipologia"] == "Abitazioni civili")
].groupby(["Anno", "Zona"]).agg(
    Compr_min=('Compr_min', 'min'),
    Compr_max=('Compr_max', 'max')
).reset_index()

omi_slim.head()

   Anno Zona  Compr_min  Compr_max
0  2015  B12       7400      11900
1  2015  B13       4900       7900
2  2015  B15       6400       9900
3  2015  B16       6400       9000
4  2015  B17       4000       7600

In [ ]:
omi_merged = omi_slim.merge(
    omi_zones,
    on='Zona',
    how='left'    
)

# Calcolo Media Geometrica (Scelta "Scientifica")
omi_merged['Estimated_Price'] = np.sqrt(
    omi_merged['Compr_min'] * omi_merged['Compr_max']
)

# Arrotonda
omi_merged['Estimated_Price'] = omi_merged['Estimated_Price'].round().astype(int)

omi_merged = gpd.GeoDataFrame(omi_merged, geometry=omi_merged['geometry'])


omi_merged.head()

,Anno,Zona,Compr_min,Compr_max,geometry,Estimated_Price
0,2015,B12,7400,11900,"POLYGON Z ((514267.639 5034915.946 0, 514284.6...",9384
1,2015,B13,4900,7900,"POLYGON Z ((513895.15 5033961.011 0, 513922.50...",6222
2,2015,B15,6400,9900,"POLYGON Z ((515245.709 5035406.626 0, 515240.7...",7960
3,2015,B16,6400,9000,"MULTIPOLYGON Z (((513779.417 5034933.409 0, 51...",7589
4,2015,B17,4000,7600,"MULTIPOLYGON Z (((509098.615 5038579.09 0, 509...",5514

In [ ]:
# Lancia il processo per visualizzare il prezzo stimato dal 2015 al 2023 in una griglia 3x3
# generate_annual_maps_grid(
#     gdf=omi_merged,
#     value_col='Estimated_Price',
#     id_col='Zona', 
#     name_col='Zona',
#     cols=3 # Visualizza 3 mappe per riga
# )

In [ ]:
house_prices_nil = interpolate_panel_data(
    source_gdf=omi_merged,
    target_gdf=nil,
    data_cols=['Compr_min', 'Compr_max'], 
    year_col="Anno", 
    target_id_col="ID_NIL",
    method = "intensive"
)

Starting interpolation for 9 periods on 2 variables...

In [ ]:
# EXPLANATION: WHY DO WE USE THE GEOMETRIC MEAN?
#"Estimated prices were calculated using the geometric mean of the Min-Max range to provide a robust estimator of the median in log-normal price distributions."

# Calcolo Media Geometrica (Scelta "Scientifica")
house_prices_nil['Estimated_Price'] = np.sqrt(
    house_prices_nil['Compr_min'] * house_prices_nil['Compr_max']
)

# Arrotonda
house_prices_nil['Estimated_Price'] = house_prices_nil['Estimated_Price']

# Selezione colonne finali
final_house_prices = house_prices_nil[['ID_NIL', 'NIL', 'Anno', 'Estimated_Price', 'geometry']].copy()
final_house_prices = final_house_prices.reset_index(drop=True)


# --- CHECK DI CURIOSITÀ (Opzionale) ---
# Vediamo quanta differenza c'è con l'aritmetica
aritmetica = (house_prices_nil['Compr_min'] + house_prices_nil['Compr_max']) / 2
diff_media = (aritmetica - house_prices_nil['Estimated_Price']).mean()
print(f"\nDifferenza media tra Aritmetica e Geometrica: {diff_media:.2f} €/mq")

final_house_prices.head()

Differenza media tra Aritmetica e Geometrica: 184.36 €/mq

,ID_NIL,NIL,Anno,Estimated_Price,geometry
0,1,DUOMO,2015,7828.64,"POLYGON ((515228.364 5035405.426, 515220.974 5..."
1,1,DUOMO,2016,7732.37,"POLYGON ((515228.364 5035405.426, 515220.974 5..."
2,1,DUOMO,2017,7789.11,"POLYGON ((515228.364 5035405.426, 515220.974 5..."
3,1,DUOMO,2018,7830.97,"POLYGON ((515228.364 5035405.426, 515220.974 5..."
4,1,DUOMO,2019,7929.04,"POLYGON ((515228.364 5035405.426, 515220.974 5..."

#### Reason
To estimate the representative property price ($P_i$) for each zone, we calculated the Geometric Mean of the minimum ($\text{Min}$) and maximum ($\text{Max}$) transaction values ($\sqrt{\text{Min} \cdot \text{Max}}$).Justification for Geometric MeanStatistical Robustness: Real estate prices typically exhibit a log-normal distribution, meaning the data is skewed by extremely high-value properties. The Geometric Mean is statistically superior to the Arithmetic Mean as it provides a more conservative and robust approximation of the true Median.Methodological Rigor: While a sensitivity analysis showed a marginal numerical difference ($\approx 32  \text{€/m}^2$) between the two means—confirming the internal homogeneity of the OMI zones—the Geometric Mean was selected and retained to ensure methodological rigor in handling price data.

In [ ]:
generate_annual_maps_grid(
    gdf=final_house_prices,
    value_col='Estimated_Price',
    id_col='ID_NIL', 
    name_col='NIL',
    cols=3
)

NameError: name 'generate_annual_maps_grid' is not defined

### Median Income (from MEF, by CAP)

In [ ]:
raw_cap_zones = gpd.read_file('../data/raw/milan/cap_italia.geojson')

cap_zones = raw_cap_zones[raw_cap_zones["comune"] == "Milano"][["cap", "geometry"]].rename(columns = {"cap" : "CAP"}).sort_values(by="CAP")
cap_zones["CAP"] = cap_zones["CAP"].astype(str)

cap_zones.head(1)

       CAP                                           geometry
678  20121  MULTIPOLYGON (((9.19166 45.46428, 9.19144 45.4...

In [ ]:
irpef_2023 = pd.read_csv('../data/raw/milan/irped2023_mef.csv', sep = ";", index_col=False)
irpef_2022 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2022.csv', sep = ";", index_col=False)
irpef_2021 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2021.csv', sep = ";", index_col=False)
irpef_2020 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2020.csv', sep = ";", index_col=False)
irpef_2019 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2019.csv', sep = ";", index_col=False)
irpef_2018 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_2018.csv', sep = ";", index_col=False)
irpef_2017 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_2017.csv', sep = ";", index_col=False)
irpef_2016 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_2016.csv', sep = ";", index_col=False)
irpef_2015 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2015.csv', sep = ";", index_col=False)

irpef_list = [irpef_2023, irpef_2022, irpef_2021, irpef_2020, irpef_2019, irpef_2018, irpef_2017, irpef_2016, irpef_2015]
raw_irpef = pd.concat(irpef_list, ignore_index=True)

/var/folders/_s/6y8y2mfs10b2xlnd_02plsxr0000gn/T/ipykernel_29739/1622680870.py:2: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  irpef_2022 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2022.csv', sep = ";", index_col=False)
/var/folders/_s/6y8y2mfs10b2xlnd_02plsxr0000gn/T/ipykernel_29739/1622680870.py:3: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  irpef_2021 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2021.csv', sep = ";", index_col=False)
/var/folders/_s/6y8y2mfs10b2xlnd_02plsxr0000gn/T/ipykernel_29739/1622680870.py:4: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  irpef_2020 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2020.csv', sep = ";", index_col=False)
/var/folders/_s/6y8y2mfs10b2xlnd_02plsxr0000gn/T/ipykernel_29739/1622680870.py:5: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  irpef_2019 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2019.csv', sep = ";", index_col=False)
/var/folders/_s/6y8y2mfs10b2xlnd_02plsxr0000gn/T/ipykernel_29739/1622680870.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  irpef_2015 = pd.read_csv('../data/raw/milan/Redditi_e_principali_variabili_IRPEF_su_base_subcomunale_CSV_2015.csv', sep = ";", index_col=False)

In [ ]:
irpef_2023.head(1)

,Anno di imposta,CAP,Codice catastale,Codice Istat Comune,Denominazione Comune,Sigla Provincia,Regione,Codice Istat Regione,Numero contribuenti,Reddito da fabbricati - Frequenza,Reddito da fabbricati - Ammontare in euro,Reddito da lavoro dipendente e assimilati - Frequenza,Reddito da lavoro dipendente e assimilati - Ammontare in euro,Reddito da pensione - Frequenza,Reddito da pensione - Ammontare in euro,Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza,Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare in euro,Reddito di spettanza dell'imprenditore in contabilita' ordinaria (comprensivo dei valori nulli) - Frequenza,Reddito di spettanza dell'imprenditore in contabilita' ordinaria (comprensivo dei valori nulli) - Ammontare in euro,Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza,Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare in euro,Reddito da partecipazione (comprensivo dei valori nulli) - Frequenza,Reddito da partecipazione (comprensivo dei valori nulli) - Ammontare in euro,Reddito imponibile - Frequenza,Reddito imponibile - Ammontare in euro,Imposta netta - Frequenza,Imposta netta - Ammontare in euro,Trattamento spettante - Frequenza,Trattamento spettante - Ammontare in euro,Reddito imponibile addizionale - Frequenza,Reddito imponibile addizionale - Ammontare in euro,Addizionale regionale dovuta - Frequenza,Addizionale regionale dovuta - Ammontare in euro,Addizionale comunale dovuta - Frequenza,Addizionale comunale dovuta - Ammontare in euro,Reddito complessivo - Frequenza,Reddito complessivo - Ammontare in euro,Reddito complessivo minore o uguale a zero euro - Frequenza,Reddito complessivo minore o uguale a zero euro - Ammontare in euro,Reddito complessivo da 0 a 10000 euro - Frequenza,Reddito complessivo da 0 a 10000 euro - Ammontare in euro,Reddito complessivo da 10000 a 15000 euro - Frequenza,Reddito complessivo da 10000 a 15000 euro - Ammontare in euro,Reddito complessivo da 15000 a 26000 euro - Frequenza,Reddito complessivo da 15000 a 26000 euro - Ammontare in euro,Reddito complessivo da 26000 a 55000 euro - Frequenza,Reddito complessivo da 26000 a 55000 euro - Ammontare in euro,Reddito complessivo da 55000 a 75000 euro - Frequenza,Reddito complessivo da 55000 a 75000 euro - Ammontare in euro,Reddito complessivo da 75000 a 120000 euro - Frequenza,Reddito complessivo da 75000 a 120000 euro - Ammontare in euro,Reddito complessivo oltre 120000 euro - Frequenza,Reddito complessivo oltre 120000 euro - Ammontare in euro
0,2023,15121,A182,6003,ALESSANDRIA,AL,Piemonte,1,48582.00,21133.00,29137478.00,27497.00,642452405.00,17674.00,414104081.00,544.00,39999798.00,71.00,5483468.00,947.00,27465820,1652.00,36987734.00,46595.00,1162977658.00,40125.00,230504233.00,5375.00,4638120.00,39675.00,1122725873.00,39101.00,23097018.00,39067.00,9751600.00,47416.00,1229184059.00,NaN,NaN,9764.00,46288879.00,4914.00,61636166.00,14129.00,294698329.00,15732.00,545717411.00,1333.00,84725964.00,1039.00,96191151.00,NaN,NaN

In [ ]:
# 1. Definiamo il set di colonne di riferimento (irpef_2023)
#    IMPORTANTE: Assicurati che le colonne siano pulite (senza spazi iniziali/finali)
#    come fatto nel passo precedente.
colonne_riferimento = set(irpef_2023.columns.str.strip())

# 2. Preparazione per i risultati
risultati_confronto = {}

# 3. Ciclo su tutti i DataFrame nella tua lista
for df in irpef_list:
    # Identifichiamo il DataFrame (assumiamo la colonna 'Anno di imposta' sia presente e corretta)
    # Prendiamo il valore dalla prima riga come identificatore
    anno = df['Anno di imposta'].iloc[0]
    
    # Pulizia e conversione delle colonne del DF corrente in un set
    colonne_correnti = set(df.columns.str.strip())
    
    # Troviamo le differenze usando le operazioni sui set:
    
    # Colonne in più: presenti nel DF corrente, ma ASSENTI nel 2023
    colonne_in_piu = list(colonne_correnti - colonne_riferimento)
    
    # Colonne in meno: presenti nel 2023, ma ASSENTI nel DF corrente
    colonne_in_meno = list(colonne_riferimento - colonne_correnti)
    
    # Se troviamo differenze, le salviamo nel dizionario
    if colonne_in_piu or colonne_in_meno:
        risultati_confronto[anno] = {
            'in_piu': colonne_in_piu,
            'in_meno': colonne_in_meno
        }

# 4. Presentazione dei Risultati
if risultati_confronto:
    print("🚨 DIFFERENZE RILEVATE RISPETTO A irpef_2023: 🚨")
    print("--------------------------------------------------")
    for anno, diff in risultati_confronto.items():
        print(f"ANNO: {anno}")
        if diff['in_piu']:
            print(f"  - Colonne in più ({len(diff['in_piu'])}): {diff['in_piu']}")
        if diff['in_meno']:
            print(f"  - Colonne mancanti ({len(diff['in_meno'])}): {diff['in_meno']}")
        print("---")
else:
    print("✅ Nessuna differenza nella struttura delle colonne rilevata tra i DataFrame.")

🚨 DIFFERENZE RILEVATE RISPETTO A irpef_2023: 🚨
--------------------------------------------------
ANNO: 2022
  - Colonne mancanti (2): ['Reddito complessivo - Frequenza', 'Reddito complessivo - Ammontare in euro']
---
ANNO: 2021
  - Colonne mancanti (2): ['Reddito complessivo - Frequenza', 'Reddito complessivo - Ammontare in euro']
---
ANNO: 2020
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (4): ['Reddito complessivo - Frequenza', 'Trattamento spettante - Ammontare in euro', 'Reddito complessivo - Ammontare in euro', 'Trattamento spettante - Frequenza']
---
ANNO: 2019
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (4): ['Reddito complessivo - Frequenza', 'Trattamento spettante - Ammontare in euro', 'Reddito complessivo - Ammontare in euro', 'Trattamento spettante - Frequenza']
---
ANNO: 2018
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (5): ['Reddito complessivo - Frequenza', 'Reddito complessivo - Ammontare in euro', 'CAP', 'Trattamento spettante - Ammontare in euro', 'Trattamento spettante - Frequenza']
---
ANNO: 2017
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (5): ['Reddito complessivo - Frequenza', 'Reddito complessivo - Ammontare in euro', 'CAP', 'Trattamento spettante - Ammontare in euro', 'Trattamento spettante - Frequenza']
---
ANNO: 2016
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (5): ['Reddito complessivo - Frequenza', 'Reddito complessivo - Ammontare in euro', 'CAP', 'Trattamento spettante - Ammontare in euro', 'Trattamento spettante - Frequenza']
---
ANNO: 2015
  - Colonne in più (2): ['Bonus spettante - Frequenza', 'Bonus spettante - Ammontare in euro']
  - Colonne mancanti (4): ['Reddito complessivo - Frequenza', 'Trattamento spettante - Ammontare in euro', 'Reddito complessivo - Ammontare in euro', 'Trattamento spettante - Frequenza']
---

In [ ]:
# 1. Aggiorniamo la mappa includendo la nuova colonna <= 0
rename_map = {
    "Anno di imposta": "Year",
    "Reddito complessivo - Frequenza": "Total_Freq",
    "Reddito complessivo minore o uguale a zero euro - Frequenza": "Freq_<=0", # NUOVA
    "Reddito complessivo da 0 a 10000 euro - Frequenza": "Freq_0_10k",
    "Reddito complessivo da 10000 a 15000 euro - Frequenza": "Freq_10k_15k",
    "Reddito complessivo da 15000 a 26000 euro - Frequenza": "Freq_15k_26k",
    "Reddito complessivo da 26000 a 55000 euro - Frequenza": "Freq_26k_55k",
    "Reddito complessivo da 55000 a 75000 euro - Frequenza": "Freq_55k_75k",
    "Reddito complessivo da 75000 a 120000 euro - Frequenza": "Freq_75k_120k",
    "Reddito complessivo oltre 120000 euro - Frequenza": "Freq_Over_120k"
}

# Lista colonne da estrarre (CAP + le chiavi del dizionario sopra)
colonne_da_estrarre = ["CAP"] + list(rename_map.keys())

def standardizza_irpef(df):
    # --- STEP 1: PULIZIA E FILTRO ---
    df.columns = df.columns.str.strip()
    df_milano = df[df["Denominazione Comune"] == "MILANO"].copy()
    
    # --- STEP 2: FIX CAP (Stringa) ---
    if "CAP" in df_milano.columns:
        df_milano["CAP"] = df_milano["CAP"].astype(str).str.replace(r'\.0$', '', regex=True)
    
    # --- STEP 3: REINDEX (Crea colonne mancanti come NaN) ---
    df_standard = df_milano.reindex(columns=colonne_da_estrarre)
    
    # --- STEP 4: RINOMINA ---
    df_finale = df_standard.rename(columns=rename_map)
    
    # --- STEP 5: GESTIONE DEI VALORI ---
    
    # A. Sostituiamo NaN con 0 nelle colonne specifiche richieste
    cols_to_fix_zero = ["Freq_Over_120k", "Freq_<=0"]
    df_finale[cols_to_fix_zero] = df_finale[cols_to_fix_zero].fillna(0)
    
    # B. Se Total_Freq è NaN, lo calcoliamo sommando le altre colonne
    # Identifichiamo tutte le colonne che iniziano con "Freq_" escludendo il Totale stesso
    cols_components = [c for c in df_finale.columns if c.startswith("Freq_") and c != "Total_Freq"]
    
    # Calcoliamo la somma per riga (trattando i NaN nei componenti come 0 per la somma)
    somma_calcolata = df_finale[cols_components].fillna(0).sum(axis=1)
    
    # Riempiamo i NaN in Total_Freq con la somma calcolata
    df_finale["Total_Freq"] = df_finale["Total_Freq"].fillna(somma_calcolata)
    
    # --- 6. CONVERSIONE INTERI ---
    # Seleziona tutte le colonne di frequenza
    cols_freq = [c for c in df_finale.columns if "Freq" in c]
    # Riempi TUTTI i NaN rimasti con 0 (sicurezza) e converti in int
    df_finale[cols_freq] = df_finale[cols_freq].fillna(0).astype(int)
    
    df_finale["CAP"] = df_finale["CAP"].astype(str)
    
    return df_finale.reset_index(drop=True)

# ---------------------------------------------------------
# APPLICAZIONE
# ---------------------------------------------------------

dfs_processati = []

# Assumiamo che 'lista_dfs_grezzi' contenga i tuoi dataframe [irpef_2015, ..., irpef_2023]
for df in irpef_list: 
    df_pulito = standardizza_irpef(df)
    dfs_processati.append(df_pulito)

# Unione finale
df_unico_milano = pd.concat(dfs_processati, ignore_index=True)

# Controllo risultato
df_unico_milano.head()

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2023,20699,20,5416,1869,3048,4217,1481,1789,2859
1,20122,2023,27941,31,8520,2526,3992,5101,1806,2375,3590
2,20123,2023,22118,15,4737,1416,3041,5290,1862,2329,3428
3,20124,2023,24671,12,4880,1729,4078,7023,2127,2413,2409
4,20125,2023,30119,6,6434,2730,6273,9883,2095,1658,1040

In [ ]:
pd.set_option('display.float_format', '{:.6f}'.format)
frequencies_col = df_unico_milano.columns[2:]

income_15 = df_unico_milano[df_unico_milano["Year"] == 2015].reset_index(drop=True)

pct_income_15 = income_15.copy()
pct_income_15[frequencies_col] = income_15[frequencies_col] / income_15[frequencies_col].sum()

income_19 = df_unico_milano[df_unico_milano["Year"] == 2019].reset_index(drop=True)

pct_income_19 = income_19.copy()
pct_income_19[frequencies_col] = income_19[frequencies_col] / income_19[frequencies_col].sum()

print(pct_income_19.sum())
pct_income_15.head(5)

CAP               2012120122201232012420125201262012720128201292...
Year                                                          76722
Total_Freq                                                 1.000000
Freq_<=0                                                   1.000000
Freq_0_10k                                                 1.000000
Freq_10k_15k                                               1.000000
Freq_15k_26k                                               1.000000
Freq_26k_55k                                               1.000000
Freq_55k_75k                                               1.000000
Freq_75k_120k                                              1.000000
Freq_Over_120k                                             1.000000
dtype: object

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2015,0.015758,0.021492,0.014587,0.010968,0.009779,0.013304,0.024269,0.034431,0.072371
1,20122,2015,0.020426,0.020571,0.018873,0.012942,0.012782,0.017291,0.033589,0.049918,0.087630
2,20123,2015,0.023774,0.033773,0.022678,0.015777,0.014711,0.021157,0.038354,0.053702,0.092417
3,20124,2015,0.025895,0.037458,0.024795,0.021212,0.020098,0.025942,0.039008,0.045125,0.050098
4,20125,2015,0.029766,0.036537,0.031372,0.029853,0.028339,0.030637,0.030637,0.028755,0.020345

In [ ]:
single_step = pct_income_15.copy().drop(columns=["Year"])
single_step[frequencies_col] = (pct_income_19[frequencies_col] - pct_income_15[frequencies_col]) / 4 #one equal step per year

tot_income_16 = df_unico_milano[df_unico_milano["Year"] == 2016].reset_index(drop=True)

income_16 = pct_income_15.copy()
income_16[frequencies_col] = income_16[frequencies_col] + single_step[frequencies_col] #add one year of interpolation
income_16[frequencies_col] = income_16[frequencies_col] * tot_income_16[frequencies_col].values #multiplication of 2016 tot values weighting it for all rows
income_16[frequencies_col] = income_16[frequencies_col].round(0).astype("Int64")
income_16["Year"] = 2016

print(income_16.sum())
income_16.head()

CAP               2012120122201232012420125201262012720128201292...
Year                                                          76608
Total_Freq                                                   972934
Freq_<=0                                                       3311
Freq_0_10k                                                   234867
Freq_10k_15k                                                 104607
Freq_15k_26k                                                 249131
Freq_26k_55k                                                 260455
Freq_55k_75k                                                  48939
Freq_75k_120k                                                 40549
Freq_Over_120k                                                31086
dtype: object

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2016,15099,121,3372,1133,2393,3334,1158,1372,2216
1,20122,2016,22529,147,5977,1769,3522,4684,1684,2040,2731
2,20123,2016,22888,154,5290,1614,3623,5390,1827,2135,2823
3,20124,2016,25194,128,5852,2204,4944,6714,1904,1824,1578
4,20125,2016,28913,111,7289,3094,7092,8001,1513,1168,633

In [ ]:
tot_income_17 = df_unico_milano[df_unico_milano["Year"] == 2017].reset_index(drop=True)

income_17 = pct_income_15.copy()
income_17[frequencies_col] = income_17[frequencies_col] + (single_step[frequencies_col] * 2 ) #add two years of interpolation
income_17[frequencies_col] = income_17[frequencies_col] * tot_income_17[frequencies_col].values #multiplication of 2017 tot values weighting it for all rows
income_17[frequencies_col] = income_17[frequencies_col].round(0).astype("Int64")
income_17["Year"] = 2017

print(income_17.sum())
income_17.head()

CAP               2012120122201232012420125201262012720128201292...
Year                                                          76646
Total_Freq                                                   983585
Freq_<=0                                                       5161
Freq_0_10k                                                   237547
Freq_10k_15k                                                 104032
Freq_15k_26k                                                 246737
Freq_26k_55k                                                 265514
Freq_55k_75k                                                  50216
Freq_75k_120k                                                 41842
Freq_Over_120k                                                32537
dtype: object

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2017,15030,265,3355,1112,2327,3265,1158,1390,2284
1,20122,2017,25460,354,7607,2172,3822,4958,1769,2122,2866
2,20123,2017,22894,306,5314,1569,3547,5371,1823,2160,2901
3,20124,2017,25470,206,5948,2178,4835,6801,1948,1877,1672
4,20125,2017,29182,158,7292,3049,7056,8178,1566,1208,663

In [ ]:
tot_income_18 = df_unico_milano[df_unico_milano["Year"] == 2018].reset_index(drop=True)

income_18 = pct_income_15.copy()
income_18[frequencies_col] = income_18[frequencies_col] + (single_step[frequencies_col] * 3) #add three years of interpolation
income_18[frequencies_col] = income_18[frequencies_col] * tot_income_18[frequencies_col].values #multiplication of 2018 tot values weighting it for all rows
income_18[frequencies_col] = income_18[frequencies_col].round(0).astype("Int64")
income_18["Year"] = 2018

print(income_18.sum())
income_18.head()

CAP               2012120122201232012420125201262012720128201292...
Year                                                          76684
Total_Freq                                                   994906
Freq_<=0                                                        411
Freq_0_10k                                                   236485
Freq_10k_15k                                                 104044
Freq_15k_26k                                                 245213
Freq_26k_55k                                                 275920
Freq_55k_75k                                                  53001
Freq_75k_120k                                                 44603
Freq_Over_120k                                                35235
dtype: object

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2018,14966,27,3285,1098,2270,3254,1190,1455,2435
1,20122,2018,28468,38,9127,2586,4130,5343,1910,2279,3111
2,20123,2018,22911,30,5255,1533,3484,5453,1869,2256,3085
3,20124,2018,25764,17,5950,2163,4743,7023,2051,1995,1834
4,20125,2018,29470,11,7180,3021,7045,8521,1667,1290,719

In [ ]:
df_finale_income = pd.concat([
    df_unico_milano[~df_unico_milano['Year'].isin([2016, 2017, 2018])], 
    income_16, 
    income_17, 
    income_18 
])

df_finale_income = df_finale_income.sort_values(by=['Year','CAP']).reset_index(drop=True)
df_finale_income.head()

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k
0,20121,2015,15139,70,3431,1122,2403,3420,1151,1365,2177
1,20122,2015,19624,67,4439,1324,3141,4445,1593,1979,2636
2,20123,2015,22840,110,5334,1614,3615,5439,1819,2129,2780
3,20124,2015,24878,122,5832,2170,4939,6669,1850,1789,1507
4,20125,2015,28597,119,7379,3054,6964,7876,1453,1140,612

In [ ]:
irpef_capgeo = df_finale_income.merge(
    cap_zones,
    on='CAP',
    how='left'    
)

irpef_capgeo = gpd.GeoDataFrame(irpef_capgeo, geometry=irpef_capgeo['geometry'])
irpef_capgeo.head(1)

,CAP,Year,Total_Freq,Freq_<=0,Freq_0_10k,Freq_10k_15k,Freq_15k_26k,Freq_26k_55k,Freq_55k_75k,Freq_75k_120k,Freq_Over_120k,geometry
0,20121,2015,15139,70,3431,1122,2403,3420,1151,1365,2177,"MULTIPOLYGON (((9.19166 45.46428, 9.19144 45.4..."

In [ ]:
irpef_nil = interpolate_panel_data(
    source_gdf=irpef_capgeo,
    target_gdf=nil,
    data_cols=['Total_Freq', "Freq_<=0", 'Freq_0_10k', 'Freq_10k_15k', 'Freq_15k_26k', 'Freq_26k_55k', 'Freq_55k_75k', 'Freq_75k_120k', 'Freq_Over_120k'], 
    year_col="Year", 
    target_id_col="ID_NIL",
    method = "extensive"
)

irpef_nil[frequencies_col] = irpef_nil[frequencies_col].round(0).astype("Int64")
irpef_nil.head()

NameError: name 'interpolate_panel_data' is not defined

In [ ]:
income_brackets = [
    (0, 10000, 'Freq_0_10k'),
    (10000, 15000, 'Freq_10k_15k'),
    (15000, 26000, 'Freq_15k_26k'),
    (26000, 55000, 'Freq_26k_55k'),
    (55000, 75000, 'Freq_55k_75k'),
    (75000, 120000, 'Freq_75k_120k'),
    (120000, 200000, 'Freq_Over_120k') 
]

def calculate_interpolated_median(row) :
    """
    Estimates the median income (I_i) for a CAP using linear interpolation 
    on grouped frequency data.
    """
    total_frequency = row['Total_Freq']
    
    if total_frequency == 0 or total_frequency is np.nan:
        return np.nan
    
    target = total_frequency / 2
    cumulative_freq = 0
    
    for lower_limit, upper_limit, freq_col in income_brackets:
        
        frequency_in_bracket = row.get(freq_col, 0)
        
        # Check if the median target falls into this bracket
        if cumulative_freq + frequency_in_bracket >= target:
            # Formula: L + ((Target - F_prev) / f_med) * w 
            
            L = lower_limit                           # Lower limit of the median class
            w = upper_limit - lower_limit             # Width of the median class
            F_prev = cumulative_freq                  # Cumulative frequency of preceding classes
            f_med = frequency_in_bracket              # Frequency of the median class itself

            estimated_median = L + ((target - F_prev) / f_med) * w
            return estimated_median
        
        # Update cumulative frequency for the next iteration
        cumulative_freq += frequency_in_bracket
        
    return np.nan # Fallback if median is not found (e.g., error in data or missing high brackets)

income_nil = irpef_nil[["ID_NIL", "NIL", "geometry", "Year"]].copy()
income_nil['Median_Income_Est'] = irpef_nil.apply(calculate_interpolated_median, axis=1)
income_nil = income_nil.rename(columns = {"Year":"Anno"})

income_nil.head(1)

,ID_NIL,NIL,geometry,Anno,Median_Income_Est
0,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2015,31157.712505

generate_annual_maps_grid(
    gdf=income_nil,
    value_col='Median_Income_Est',
    id_col='ID_NIL', 
    name_col='NIL',
    year_col='Year',
    cols=3
)

## Gentrification Index

In [ ]:
# ... (Il tuo codice precedente)
df_gentr = income_nil.merge(
    final_house_prices[["Anno", "ID_NIL", "Estimated_Price"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

df_gentr["rank_income"] = df_gentr.groupby('Anno')['Median_Income_Est'].rank(pct=True)
df_gentr["rank_price"] = df_gentr.groupby('Anno')['Estimated_Price'].rank(pct=True)

# --- COMPLETAMENTO ---

# 1. Calcolo del Gentrification Gap Index (Statico)
# Gap > 0: Il quartiere ha prezzi troppo alti per i redditi dei residenti (Pressione)
# Gap < 0: Il quartiere è "sottovalutato" o ricco
df_gentr["Gentrification_Gap"] = df_gentr["rank_price"] - df_gentr["rank_income"]

# 2. Ordinamento (CRUCIALE prima di usare shift)
# Assicuriamoci che per ogni NIL gli anni siano sequenziali (2015, 2016...)
df_gentr = df_gentr.sort_values(by=["ID_NIL", "Anno"])

# 3. Implementazione Rolling Window (Look-Ahead di 4 anni)
# shift(-4) prende il valore che si trova 4 righe SOTTO (nel futuro) e lo porta nella riga corrente
df_gentr["Gap_Future"] = df_gentr.groupby("ID_NIL")["Gentrification_Gap"].shift(-4)

# 4. Calcolo del Target Finale (Delta)
# Target = (Gap tra 4 anni) - (Gap Oggi)
df_gentr["Target_Delta_Gap"] = df_gentr["Gap_Future"] - df_gentr["Gentrification_Gap"]



# Funzione lambda per calcolare Z-Score: (Valore - Media) / Deviazione Standard
z_score_func = lambda x: (x - x.mean()) / x.std()

# ---------------------------------------------------------
# APPLICAZIONE NORMALIZZAZIONE (City-Year)
# ---------------------------------------------------------

# 1. Normalizzazione PREZZI
# Raggruppa per Città E Anno -> Calcola Z-Score dentro quel gruppo
#df_gentr['Price_Z'] = df_gentr.groupby(['City', 'Anno'])['Estimated_Price'].transform(z_score_func)
df_gentr['Price_Z'] = df_gentr.groupby('Anno')['Estimated_Price'].transform(z_score_func)

# 2. Normalizzazione REDDITI
df_gentr['Income_Z'] = df_gentr.groupby('Anno')['Median_Income_Est'].transform(z_score_func)

# --- VERIFICA ---
# Controlliamo che la media sia ~0 e la std sia ~1 per un gruppo a caso (es. Milano 2015)
#subset_check = df_gentr[(df_gentr['City'] == 'Milano') & (df_gentr['Anno'] == 2015)]
subset_check = df_gentr[(df_gentr['Anno'] == 2019)]

print("Esempio Milano 2015 (dopo normalizzazione):")
print(f"Media Price_Z: {subset_check['Price_Z'].mean():.4f} (Deve essere ~0)")
print(f"Std Price_Z:   {subset_check['Price_Z'].std():.4f} (Deve essere ~1)")

# Visualizziamo le differenze
print("\nConfronto Valori Assoluti vs Z-Score:")
#print(df_gentr[['City', 'Anno', 'Estimated_Price', 'Price_Z', 'Median_Income_Est', 'Income_Z']].head())
print(df_gentr[['Anno', 'Estimated_Price', 'Price_Z', 'Median_Income_Est', 'Income_Z']].head())

# valori sarebbero tipo 3.5 == +3.5 rispetto alla media di Milano 2015
df_gentr.head(10)

Esempio Milano 2015 (dopo normalizzazione):
Media Price_Z: -0.0000 (Deve essere ~0)
Std Price_Z:   1.0000 (Deve essere ~1)

Confronto Valori Assoluti vs Z-Score:
   Anno  Estimated_Price  Price_Z  Median_Income_Est  Income_Z
0  2015      7828.643861 3.548526       31157.712505  2.637435
1  2016      7732.369884 3.490392       29427.937217  2.154524
2  2017      7789.113076 3.509105       27957.045159  1.626055
3  2018      7830.973363 3.530724       26994.748072  1.197740
4  2019      7929.035919 3.472054       25641.388175  0.768354

,ID_NIL,NIL,geometry,Anno,Median_Income_Est,Estimated_Price,rank_income,rank_price,Gentrification_Gap,Gap_Future,Target_Delta_Gap,Price_Z,Income_Z
0,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2015,31157.712505,7828.643861,0.977273,1.000000,0.022727,0.170455,0.147727,3.548526,2.637435
1,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2016,29427.937217,7732.369884,0.965909,1.000000,0.034091,0.147727,0.113636,3.490392,2.154524
2,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2017,27957.045159,7789.113076,0.909091,1.000000,0.090909,0.193182,0.102273,3.509105,1.626055
3,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2018,26994.748072,7830.973363,0.897727,1.000000,0.102273,0.193182,0.090909,3.530724,1.197740
4,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2019,25641.388175,7929.035919,0.829545,1.000000,0.170455,0.215107,0.044652,3.472054,0.768354
5,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2020,26236.408519,8015.251369,0.852273,1.000000,0.147727,NaN,NaN,3.375385,0.829187
6,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2021,26154.325181,8040.824778,0.806818,1.000000,0.193182,NaN,NaN,3.189490,0.710230
7,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2022,27008.632249,8482.016583,0.806818,1.000000,0.193182,NaN,NaN,2.963201,0.664780
8,1,DUOMO,"POLYGON ((515228.364 5035405.426, 515220.974 5...",2023,27955.874577,8576.655411,0.761364,0.976471,0.215107,NaN,NaN,2.628679,0.553961
9,2,BRERA,"POLYGON ((514980.845 5035076.611, 515011.579 5...",2015,27603.705832,6803.188161,0.931818,0.976471,0.044652,0.044652,0.000000,2.773657,1.625413

## Inside Airbnb

In [ ]:
airbnb = pd.read_csv('../data/raw/milan/inside_.csv', sep = ";", index_col=False)

## Merging Phase

In [ ]:
df = final_house_prices.copy()
df = df.drop(columns="geometry")

df = df.merge(
    densita_nil[["Anno", "ID_NIL", "Pop_density"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

df = df.merge(
    young_adults[["Anno", "ID_NIL", "pct_young_adults"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

df = df.merge(
    income_nil[["Anno", "ID_NIL", "Median_Income_Est"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

df = df.merge(
    df_gentr[["Anno", "ID_NIL", "Price_Z",	"Income_Z", "Gentrification_Gap", "Target_Delta_Gap"]],
    on=["Anno", "ID_NIL"],
    how='left'
)

df_train = df.dropna(subset=['Target_Delta_Gap']).copy()


# save df_train to csv
df_train.to_csv("../data/preprocessed/milan/panel_data_milan.csv", index=False)

df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 425 entries, 0 to 760
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID_NIL              425 non-null    int32
 1   NIL                 425 non-null    object
 2   Anno                425 non-null    int64
 3   Estimated_Price     425 non-null    float64
 4   Pop_density         425 non-null    float64
 5   pct_young_adults    422 non-null    float64
 6   Median_Income_Est   425 non-null    float64
 7   Price_Z             425 non-null    float64
 8   Income_Z            425 non-null    float64
 9   Gentrification_Gap  425 non-null    float64
 10  Target_Delta_Gap    425 non-null    float64
dtypes: float64(8), int32(1), int64(1), object(1)
memory usage: 38.2+ KB